# bytes_literal_with_em_dash.py
# INVALID ENCODING TEST CASE 1 (auto-generated by create_test_fixtures.py)
#
# Bytes literal containing U+2014 (em dash) -- invalid per PEP 3120.
# semgrep raises: "bytes can only contain ASCII literal characters"
#
# Expected: scan completes, file in files.sast_skipped_files, no findings.

import base64

SECRET_TOKEN = "sk-prod-abc123def456"  # Would be a finding IF the file parsed

_PAYLOAD = base64.b64encode(b"""
def run():
    # Simulated —  runs on import
    pass
""")
