#!/usr/bin/env python3
# Copyright © 2026 Sthenos Security. All rights reserved.
"""
create_test_fixtures.py — generate the actual binary/encoding-broken test files.

Run once after cloning:
    python3 invalid-encoding-test/create_test_fixtures.py

The Filesystem write tool writes UTF-8, so files that must contain
non-UTF-8 bytes need to be created programmatically.
"""

import os
from pathlib import Path

HERE = Path(__file__).parent


def create_bytes_literal_with_em_dash():
    """
    Test case 1: bytes literal (b\"\"\"...\"\"\") containing a UTF-8 em dash (U+2014).
    Python rejects this at parse time: 'bytes can only contain ASCII literal characters'.
    This is the exact pattern that broke muaddib-simulation/setup.py.
    """
    em_dash = "\u2014".encode("utf-8")  # 0xe2 0x80 0x94

    preamble = (
        b"# bytes_literal_with_em_dash.py\n"
        b"# INVALID ENCODING TEST CASE 1 (auto-generated by create_test_fixtures.py)\n"
        b"#\n"
        b"# Bytes literal containing U+2014 (em dash) -- invalid per PEP 3120.\n"
        b"# semgrep raises: \"bytes can only contain ASCII literal characters\"\n"
        b"#\n"
        b"# Expected: scan completes, file in files.sast_skipped_files, no findings.\n"
        b"\n"
        b"import base64\n"
        b"\n"
        b"SECRET_TOKEN = \"sk-prod-abc123def456\"  # Would be a finding IF the file parsed\n"
        b"\n"
        b"_PAYLOAD = base64.b64encode(b\"\"\"\n"
        b"def run():\n"
        b"    # Simulated "
    )
    suffix = (
        b"  runs on import\n"
        b"    pass\n"
        b"\"\"\")\n"
    )
    content = preamble + em_dash + suffix

    out = HERE / "bytes_literal_with_em_dash.py"
    out.write_bytes(content)
    print(f"  Created: {out} ({len(content)} bytes)")

    # Verify Python rejects it
    import py_compile
    import tempfile
    with tempfile.NamedTemporaryFile(suffix=".py", delete=False) as tmp:
        tmp.write(content)
        tmp_path = tmp.name
    try:
        py_compile.compile(tmp_path, doraise=True)
        print("  ERROR: should have failed!")
    except py_compile.PyCompileError:
        print("  Verified: Python rejects it as expected")
    finally:
        os.unlink(tmp_path)


def create_latin1_no_declaration():
    """
    Test case 2: Latin-1 encoded file with no coding declaration.
    Python 3 assumes UTF-8; Latin-1 bytes 0x80-0xFF are not valid UTF-8.
    Real-world: legacy PHP, Python 2, Windows-1252 source files.
    """
    content = (
        "# latin1_no_declaration.py\n"
        "# INVALID ENCODING TEST CASE 2 (auto-generated by create_test_fixtures.py)\n"
        "#\n"
        "# Latin-1 file without '# -*- coding: latin-1 -*-' declaration.\n"
        "# semgrep raises: UTF-8 decode error (byte 0xe9 is not valid UTF-8).\n"
        "#\n"
        "# Expected: scan completes, file in files.sast_skipped_files, no findings.\n"
        "\n"
        "import os\n"
        "\n"
        'AUTHOR = "Ren\xe9 Descartes"           # Latin-1: 0xe9 = \xe9\n'
        'API_KEY = "hardcoded-api-key-abc123"  # Would be a finding IF the file parsed\n'
        "\n"
        "def compute():\n"
        '    """Compute something na\xefve."""\n'
        '    caf\xe9_count = int(os.environ.get("CAFE_COUNT", 0))\n'
        "    return caf\xe9_count\n"
    ).encode("latin-1")

    out = HERE / "latin1_no_declaration.py"
    out.write_bytes(content)
    print(f"  Created: {out} ({len(content)} bytes)")

    import py_compile
    import tempfile
    with tempfile.NamedTemporaryFile(suffix=".py", delete=False) as tmp:
        tmp.write(content)
        tmp_path = tmp.name
    try:
        py_compile.compile(tmp_path, doraise=True)
        print("  ERROR: should have failed!")
    except (py_compile.PyCompileError, SyntaxError):
        print("  Verified: Python rejects it as expected")
    finally:
        os.unlink(tmp_path)


def create_binary_disguised_as_python():
    """
    Test case 3: binary bytes (ELF header + null bytes) in a .py file.
    Simulates a corrupted file or binary accidentally given .py extension.
    """
    header = (
        b"# binary_disguised_as_python.py\n"
        b"# INVALID ENCODING TEST CASE 3 (auto-generated by create_test_fixtures.py)\n"
        b"#\n"
        b"# Raw binary bytes (ELF magic + nulls) in a .py file.\n"
        b"# Simulates corrupted source or binary with wrong extension.\n"
        b"# semgrep raises: source code string cannot contain null bytes.\n"
        b"#\n"
        b"# Expected: scan completes, file in files.sast_skipped_files, no findings.\n"
        b"\n"
    )
    binary_blob = bytes([
        0x7f, 0x45, 0x4c, 0x46,  # ELF magic
        0x02, 0x01, 0x01, 0x00,
        0x00, 0x00, 0x00, 0x00,  # null bytes
        0x00, 0x00, 0x00, 0x00,
        0x02, 0x00, 0x3e, 0x00,
        0x00, 0x00, 0x00, 0x00,  # more nulls
        0xff, 0xfe, 0xfd, 0xfc,  # high bytes
    ])
    content = header + binary_blob

    out = HERE / "binary_disguised_as_python.py"
    out.write_bytes(content)
    print(f"  Created: {out} ({len(content)} bytes)")

    import py_compile
    import tempfile
    with tempfile.NamedTemporaryFile(suffix=".py", delete=False) as tmp:
        tmp.write(content)
        tmp_path = tmp.name
    try:
        py_compile.compile(tmp_path, doraise=True)
        print("  ERROR: should have failed!")
    except (py_compile.PyCompileError, SyntaxError, UnicodeDecodeError):
        print("  Verified: Python rejects it as expected")
    finally:
        os.unlink(tmp_path)


if __name__ == "__main__":
    print("Creating invalid-encoding test fixtures...")
    create_bytes_literal_with_em_dash()
    create_latin1_no_declaration()
    create_binary_disguised_as_python()
    print("Done. Run: reachctl scan invalid-encoding-test/ and verify sast_skipped_files == 3")
