# latin1_no_declaration.py
# INVALID ENCODING TEST CASE 2 (auto-generated by create_test_fixtures.py)
#
# Latin-1 file without '# -*- coding: latin-1 -*-' declaration.
# semgrep raises: UTF-8 decode error (byte 0xe9 is not valid UTF-8).
#
# Expected: scan completes, file in files.sast_skipped_files, no findings.

import os

AUTHOR = "René Descartes"           # Latin-1: 0xe9 = é
API_KEY = "hardcoded-api-key-abc123"  # Would be a finding IF the file parsed

def compute():
    """Compute something naïve."""
    café_count = int(os.environ.get("CAFE_COUNT", 0))
    return café_count
